### ISSUE TITLE
Multiple tag editing submission

### ISSUE THREAD

**Issue by Mirdarthos** [BoostIO/BoostNote.next-local#11]
# Current behavior
Currently, when adding tags to a note, if I select a tag with the keyboard and press <kbd>Enter</kbd> to seeleect itt, it seleects it and closes the selection list.

# Expected behavior
Select and add the tag, as it currently does, but afterwards, keep the tag list open and the focus on the tag list search input field, so that another tag can easily be searched and added.

Alternatively, leave it exactly this way but add a sepeerate, say <kbd>Ctrl</kbd>+<kbd>Enter</kbd> for the submit and add another tag functionality.

# Steps to reproduce
Add multiple tags to a note.

# Environment
Linux Desktop (but I'm sure it would be useful for other environments as well. Like Web.)

## Desktop/Web
- Boost Note.next local version: 0.21.1
- OS version and name: Manjaro Linux 21.1.0

**Comment by Komediruzecki** [comment]
This has been implemented, merged and waiting for next release with few more fixes and improvements.

Please reopen if needed, after the release.
