### ISSUE TITLE
I can't add an external storage from Synology NAS

### ISSUE THREAD

**Issue by zak39** [BoostIO/BoostNote.next-local#14]
# Current behavior

# Expected behavior

Hi everyone 👋 

I use boostnote daily and I would like to share my notes between my devices (laptop and desktop).

But, I didn't add external storage from my Windows 10 pro :/

# Steps to reproduce

1. Open the folder shared from File Explorator (example: `\\Your_Synology_NAS\Note_Shared`
2. Open Boostnote application and click on *Create a space*
3. Then, click on *Create a local space without creating an account*
4. Define the space type on *File System*, then click on  *Select Folder* and select the folder shared `\\Your_Synology_NAS\Note_Shared`
5. Then, click on *Create Space* button and you have the error (see the screen shot below). Here is the error message : `Something went wrong - TypeError: Cannot read property '/' of undefined`

![image](https://user-images.githubusercontent.com/28636549/120077008-8991bb00-c0a8-11eb-9e72-379b8ac12575.png)

# Environment

- Boostnote version: 0.14.1
- OS version and name: Windows 10 Professionnel / 20H2 release

Thank you 😃

**Comment by Komediruzecki** [comment]
We inspected this a bunch more privately and I think this is resolved, the latest local space application will also better handle loading corrupted storages and data so it should have more capability on debugging storages.

Please reopen if needed.

**Comment by llorllale** [comment]
I'm getting this same error when trying to add my legacy space into boostnote.next.

What was the outcome of this investigation in the end? How can I troubleshoot this?

**Comment by Komediruzecki** [comment]
> I'm getting this same error when trying to add my legacy space into boostnote.next.
> 
> What was the outcome of this investigation in the end? How can I troubleshoot this?
> 
> Edit: also trying to work around this by exporting from legacy (in .md format) and attempting to import into boostnote.next but I don't see the import option...

You need to use the not latest version of boost note local space, after importing through the legacy importer, you can install the latest and load the converted boost note next to local storage/space.

You can use 0.19.x to import from legacy then go to the local space repository and download the latest local space app to load converted storage.

**Comment by llorllale** [comment]
Thanks but well... I just ended up biting the bullet and spending about 90 minutes of focused work just copying the notes over.
