### ISSUE TITLE
Remove all archived documents

### ISSUE THREAD

**Issue by Xiang929** [BoostIO/BoostNote.next-local#17]
how to empty archive after deleting a lot of documents （local space)
# Environment

## Desktop
- Boost Note.next version: <0.20.1>
- OS version and name: <macOS>

**Comment by Komediruzecki** [comment]
I'll see to add this into boost note local roadmap 2021/2022 so we can implement some sort of bulk actions on various parts of the application (moving, bookmarking, deleting, archiving...)

I'll post the roadmap soon!

**Comment by Komediruzecki** [comment]
Roadmap posted: https://github.com/BoostIO/BoostNote.next-local/projects/1

**Comment by Komediruzecki** [comment]
Implemented and will be soon released.
