### ISSUE TITLE
Display local space information

### ISSUE THREAD

**Issue by Rokt33r** [BoostIO/BoostNote.next-local#34]
# Current behavior

There is no UI displaying local space's information like its actual location.

# Expected behavior

Should show it from preferences or introduce a storage setting page.

# Environment

- Boost Note.next version: v0.21.1
- OS version and name:

**Comment by Komediruzecki** [comment]
Fixed in the release: https://github.com/BoostIO/BoostNote.next-local/releases/tag/v0.22.3
