### ISSUE TITLE
Sort labels alphabetically.

### ISSUE THREAD

**Issue by barnizyparafina** [BoostIO/BoostNote.next-local#55]
# Current behavior

Labels are ordered according to their creation date. This seems a bit awkward to me when looking for a particular tag.

# Expected behavior

The labels section should have a drop-down menu from which the labels can be sorted by "Creation date" "Counter" and "Alphabetically".

![Captura de pantalla de 2021-10-24 09-23-30](https://user-images.githubusercontent.com/55588629/138598438-7633f9a0-7526-438d-baea-6d06badeabbc.png)

# Steps to reproduce

1. Open Boostnote.
2. Try to order labels in alphabetically order.

# Environment

- Boost Note.next version: 
- OS version and name:

**Comment by Komediruzecki** [comment]
Actually, you drive this label sorting with the same option as note sorting in Preferences.

So you can sort them alphabetically, but that will sort the notes as well, so I'll just make 2 distinct options and it should work nicely.

**Comment by Komediruzecki** [comment]
Will be released soon, implemented.
