### ISSUE TITLE
Interacting with checkboxes repositions editor view to the top 

### ISSUE THREAD

**Issue by emcangi** [BoostIO/BoostNote.next-local#56]
# Current behavior

In longer notes that also have checkboxes lower down, interacting with the checkbox causes the editor to scroll back up to the top of the page.

See here for before/after shots: https://imgur.com/a/trK710B

I didn't have the dev tools open in the first because it didn't seem to be showing anything, but I opened them later.

# Expected behavior

Interacting with a checkbox should not cause the editor view to change.

# Steps to reproduce

1. Make a note with several paragraphs of text
2. put a checkbox in it
3. scroll editor and viewer to checkbox
4. check the box and observe the behavior
5. you can also uncheck the box and it will do it again 

# Environment

- Boost Note.next version: 0.22.3
- OS version and name: Ubuntu 21.10

**Comment by Komediruzecki** [comment]
@emcangi I made some updates,

Now it will re-focus on the middle of the current line instead of going to the top.
The editor stays focused so you can continue writing after changing the checkbox.

Maybe we could also jump to the changed checkbox line, but this seems a bit too much automation.
