### ISSUE TITLE
How to load multiple spaces

### ISSUE THREAD

**Issue by rabbit0v0** [BoostIO/BoostNote.next-local#58]
I cannot find a way to load more than one space and also seems I can't delete files.

**Comment by Komediruzecki** [comment]
Hi, to add another space, you need to go to create space page, you can access it via File menu or from right clicking on navigator.

For deleting, currently the model is to archive a note, then you can look into archived/trashed notes and delete it from there.

**Comment by Komediruzecki** [comment]
I will close this because of inactivity, if in need, please open a new one.
