### ISSUE TITLE
Color Text - 

### ISSUE THREAD

**Issue by MalekJabri** [BoostIO/BoostNote.next-local#62]
Hi,

I can add a simple HTML marker to the text like bold but when I tried to change the text colour nothing is working. 
is it a limitation of the Boost Note local we don't have the Sanitizazion option?

I want a feature render text in special color:

#347E5E --> <p style="color: #347E5E">#347E5E</p>

# Environment

- Boost Note - Local 0.21.1
- OS version and name:  Mac os Big sur

**Comment by Komediruzecki** [comment]
Hello,

the color is not supported in HTML at the moment, but you can try adding math blocks that are colored, see example:
`$\color{#FF0FFF} Colored \space Items$`

![image](https://user-images.githubusercontent.com/18196945/147663924-a5a936c6-21ec-456e-bdd5-5b8b61ba93a2.png)

**Comment by Komediruzecki** [comment]
I am going to close this issue for now if you still need this, please reopen another one.
