### ISSUE TITLE
Surrounding of text with quotes, brackets, backticks etc.

### ISSUE THREAD

**Issue by mikmaksi** [BoostIO/BoostNote.next-local#66]
# Current behavior

There does not appear to be a way to surround selected text in quotes or other markdown characters like *,$,` .

# Expected behavior

1. Select text. 
2. Type the character you want to surround text with, for example "[". 
3. "[" is then added before selected text and the bracket is closed with "]" at the end of selected text.

# Environment

- Boost Note.next version: 0.22.3
- OS version and name: macOS Monterey 12.2.1

**Comment by Komediruzecki** [comment]
Hello,

I agree, it would be nice to have some editor toolbar for formatting the text.

I added initial implementation here: https://github.com/BoostIO/BoostNote.next-local/pull/67
You can look at the showcase, I also added math and brackets insertion, but there are currently no shortcuts to do so.

Let me know if this is what you intended?

**Comment by Komediruzecki** [comment]
Implemented most of it.

Backtick surrounding not yet, but maybe it will be in next release.
