### ISSUE TITLE
Add Rename/Delete/Export options to Tags

### ISSUE THREAD

**Issue by barnizyparafina** [BoostIO/BoostNote.next-local#82]
# Current behavior

Tags doesn't have the Rename/Delete/Export options.

![boostnote-tags-actual](https://user-images.githubusercontent.com/55588629/165434940-c8b03739-a65c-45bb-9b5e-847ce97ee895.png)

# Proposed behavior

Put the same button of options that the folders.
I created a visual example of this:

![Boostnote-tags](https://user-images.githubusercontent.com/55588629/165434621-d5b327a3-80fb-431b-af2c-600eeb306703.png)

**Comment by Komediruzecki** [comment]
Hi,

I don't know if we want to have the remove tag option, what would it do?
The tag is removed once no note contains it, removing it would be destructive for all such notes, is it necessary?

As for the export tag, what would that option do it? Export all notes with that tag? That would make sense, I'll see what I can do about it.

**Comment by barnizyparafina** [comment]
> Hi,
> 
> I don't know if we want to have the remove tag option, what would it do? The tag is removed once no note contains it, removing it would be destructive for all such notes, is it necessary?
> 
> As for the export tag, what would that option do it? Export all notes with that tag? That would make sense, I'll see what I can do about it.
> 
> and the last one, you probably meant rename? That would also be a nice feature, I'll see to implement it for next release.

Komediruzecki, thanks very much for your reply.

The Remove tag option would remove the tag from all notes that contains this tag. That option exist in Gmail, you can remove a tag, and the mails that contains this tag remove this tag of its group of tags. In some ocations, that can be useful.

Yes, I meant _Rename_. I have just edited the issue.

**Comment by Komediruzecki** [comment]
Implemented here: #85
