### ISSUE TITLE
Remove the Ctrl+W Keybind

### ISSUE THREAD

**Issue by barnizyparafina** [BoostIO/BoostNote.next-local#83]
# Current behavior

Boostnote closes when the Ctrl+W Keybind is pressed. That is from my point of view uncomfortable, especially because the keybind of change the Edit-mode to Preview-mode is Ctrl+E, and 'w' and 'e' are next to each other.

# Expected behavior

Remove the Ctrl+W Keybind completely or else add the option to disable this in preferences.

# Environment

- Boost Note.next version: 0.23.0

**Comment by Komediruzecki** [comment]
Hi,

oh, really sorry, didn't want this cannot be changed.

I'll add a custom keymap for it, so you can un-assign it or bind it to another key.

There is already `Ctrl+Q` which quits the window.
