### ISSUE TITLE
Import failed - typeerror cannot read property '/' of undefined

### ISSUE THREAD

**Issue by bilalinamdar** [BoostIO/BoostNote.next-local#87]
Hi,
When i am trying to import my notes it is giving me this error
typeerror cannot read property '/' of undefined
Please assist. PFA for error screenshot

Regards,
Bilal Inamdar

![Boost_Note_-_Local_aKl9NTsptD](https://user-images.githubusercontent.com/7912006/177050105-25f299df-d3ed-45d2-9b57-912914dc3e88.png)

**Comment by Komediruzecki** [comment]
Hi, 

sorry for long await, I saw the issue, 

The error message is usually if you are importing from invalid or wrong boost note into new boost note next storage.

Can you show me how does your location and boostnote.json looks like, are you importing legacy storage into new boost note?

You need to first create an empty space / new space, and then in Preferences you can import legacy notes.

If you are importing previous boost note next storage, then we need to see why its failing (boostnote.json and folder location should be inspected and made sure no invalid data is there or multiple storages)

Please let me know about the details of your versions and what are you trying to achieve.

**Comment by Komediruzecki** [comment]
Few resolved things or similar issue you can see here: https://github.com/BoostIO/BoostNote.next-local/discussions/53

**Comment by bilalinamdar** [comment]
Hi,
As per suggestion I tried BOOST NOTE 19 version. It gave same error.

Here is the boostnote.json content
boostnote.json contain only this data
`{
  "folders": [],
  "version": "1.0"
}
`

I don't remember exactly what was the previous version. So I am unsure on answering that.

You can also suggest me exactly which version i should install and can import the json files. Although the structure which i made will be disturbed but atleast i will get my data.

I have had really big hopes after shifting from snippets (snippets.me) to boostnote but it seems due to the race of commercialization basic features are been taken away from free users.

**Comment by Komediruzecki** [comment]
HI this looks like the legacy storage, in that case proceed with latest boost note next and create a empty space, after that in preferences you will find import from legacy option and load it there.

But your boostnote json looks empty, no folders, so it might of got overwritten, in that case do you have a backup?

Please backup any previous storage data and notes you have before importing into new one so you have it safe somewhere.

Then try loading it in app, the legacy notes should be in CSON format, do you have such files on your file system,  you don't have to send them here just confirm.

For sending any data, you can contact me on our slack.

Or if you want to speed conversation.

If you have notes folder with JSON files, then you had boostnote next before, in that case it should load normally given you don't have corrupted storage.

**Comment by bilalinamdar** [comment]
Hi,
Sorry for delayed response.
It is all in JSON. I can't find any CSON.
I am confused on why the storage will be corrupt because i do 3 level backup (cloud + local + ext disk).
I have very few notes which i written this year.
So how i can manually import them to any boost note ? Can't i just copy paste from the json file / notepad++ to the boostnote.

Regards,
Bilal Inamdar

**Comment by Komediruzecki** [comment]
Hi,

I would need to inspect the storage folder for that insight, you probably have some hidden or invalid files in your folder where your storage location is, you should only have notes and attachments folders, and boostnote.json file.

In notes should be only *. Json files and nothing else, no extra folders, in attachments folder just *.png files.

Yes, you could open json text files and copy content manually of course.

Just don't put same storage space location in boost note for new storage, because it should be an empty folder where your new empty storage should be, everything else, boostnote will create and update as needed.

**Comment by Komediruzecki** [comment]
Closing as resolved, if you experience similar issue again, please reopen the issue.
