### ISSUE TITLE
Boost Note 0.21.1 doesnt work at all!

### ISSUE THREAD

**Issue by baermathias** [BoostIO/BoostNote.next-local#9]
# Current behavior

Clicking on file and then the following menu options doesn't do anything:
New Note
New Folder 
Save As
Add Cloud Space
Add Local Space

The only options which works is "Preferences"

Also the following menu is completely empty when clicking it:
![Screenshot from 2021-08-19 08-37-21](https://user-images.githubusercontent.com/45003352/130020085-f6be406e-8396-42b1-94dd-aea14ba3d570.png)

# Expected behavior

Open the menus. Do something.

# Steps to reproduce

1. Download .deb file
2. install
3. run

# Environment

- Boost Note.next version: 0.21.1
- OS version and name: Ubuntu 20.04

**Comment by Komediruzecki** [comment]
Hi, 

This is the default and wanted behavior, sorry for not documenting this better.

From this new only local desktop application, you need to import your previous storage into the application, this was done to ensure no deprecated storages (all but local file system storage) is allowed or transferred.

You need to create yourself a new local file system space (on the page you are currently looking) by adding a name and location then clicking on 'Create space' button below.
The application does not support local storage (browser-based) anymore so you cannot directly add files/folders without creating a space and location.

We could fix this by having some sort of default storage location, but it might be unwanted for some users to create it somewhere on disk on application startup. But we should definitely fix the intro screen and have a note saying what changed (this is a feature I am working on, we would like to have real changelog and changelist across application updates)

Thank you for understanding, and please if you have any other questions, don't hesitate to ask!

**Comment by Komediruzecki** [comment]
Fixed in release: https://github.com/BoostIO/BoostNote.next-local/releases/tag/v0.22.3

The storage load/create page is now standalone - without the navigator
